# Generated by Django 5.1.1 on 2024-12-03 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialSound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallealbum',
            name='album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_album', to='socialSound.album'),
        ),
    ]
