# Generated by Django 5.1.4 on 2025-01-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialSound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nac',
            field=models.DateField(null=True),
        ),
    ]
