# Generated by Django 5.1.5 on 2025-01-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialSound', '0002_alter_usuario_fecha_nac'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='acepta_terminos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='artista_favorito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero_favorito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='moderador',
            name='area_especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='moderador',
            name='codigo_moderador',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='moderador',
            name='experiencia_moderacion',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
