# Generated by Django 5.1.1 on 2024-12-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialSound', '0003_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallescancion',
            name='duracion',
            field=models.DurationField(default=0),
        ),
    ]
