# Generated by Django 5.1.1 on 2024-12-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialSound', '0004_alter_detallescancion_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallescancion',
            name='duracion',
            field=models.DurationField(blank=True, default=0),
        ),
    ]
